### ISSUE TITLE
[BUG] test failed

### ISSUE THREAD

**Issue by takatoyamada** [rise-lang/shine#236]
I'm new to shine compiler, and encountered the weird following error when I ran `sbt "testOnly apps.asum"`.
It seems the error to have some malformed character in the file name like λ because it emitted the line below. (I'm not very sure)
Is there anyone who knows about it?

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /workspaces/shine/target/scala-2.13/classes/shine/DPIA/DSL/λ$.class
```

**The full error message**
```
> sbt "testOnly apps.asum"
[info] welcome to sbt 1.6.2 (Private Build Java 1.8.0_312)
[info] loading settings for project shine-build from plugins.sbt ...
[info] loading project definition from /workspaces/shine/project
[info] loading settings for project riseAndShine from build.sbt ...
[info] loading settings for project arithExpr from build.sbt ...
[info] loading settings for project executor from build.sbt ...
[info] loading settings for project CUexecutor from build.sbt ...
[info] loading settings for project elevate from build.sbt ...
[info] set current project to riseAndShine (in build file:/workspaces/shine/)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for CUexecutor / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for executor / Test / testOnly
[info] compiling 485 Scala sources to /workspaces/shine/target/scala-2.13/classes ...
[error] ## Exception when compiling 485 sources to /workspaces/shine/target/scala-2.13/classes
[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /workspaces/shine/target/scala-2.13/classes/shine/DPIA/DSL/λ$.class
[error] sun.nio.fs.UnixPath.encode(UnixPath.java:147)
[error] sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
[error] sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
[error] java.io.File.toPath(File.java:2273)
[error] xsbt.API.$anonfun$registerGeneratedClasses$2(API.scala:158)
[error] xsbt.API.$anonfun$registerGeneratedClasses$2$adapted(API.scala:155)
[error] scala.Option.foreach(Option.scala:437)
[error] xsbt.API.registerProductNames$1(API.scala:155)
[error] xsbt.API.$anonfun$registerGeneratedClasses$1(API.scala:171)
[error] xsbt.API.$anonfun$registerGeneratedClasses$1$adapted(API.scala:129)
[error] scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error] scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
[error] xsbt.API.registerGeneratedClasses(API.scala:129)
[error] xsbt.API$ApiPhase.run(API.scala:38)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error] scala.tools.nsc.Global$Run.compileFiles(Global.scala:1605)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /workspaces/shine/target/scala-2.13/classes/shine/DPIA/DSL/λ$.class
[error]         at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
[error]         at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
[error]         at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
[error]         at java.io.File.toPath(File.java:2273)
[error]         at xsbt.API.$anonfun$registerGeneratedClasses$2(API.scala:158)
[error]         at xsbt.API.$anonfun$registerGeneratedClasses$2$adapted(API.scala:155)
[error]         at scala.Option.foreach(Option.scala:437)
[error]         at xsbt.API.registerProductNames$1(API.scala:155)
[error]         at xsbt.API.$anonfun$registerGeneratedClasses$1(API.scala:171)
[error]         at xsbt.API.$anonfun$registerGeneratedClasses$1$adapted(API.scala:129)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1279)
[error]         at xsbt.API.registerGeneratedClasses(API.scala:129)
[error]         at xsbt.API$ApiPhase.run(API.scala:38)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error]         at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1605)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error]         at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error]         at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:177)
[error]         at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:175)
[error]         at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:461)
[error]         at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error]         at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error]         at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:416)
[error]         at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:503)
[error]         at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:403)
[error]         at sbt.internal.inc.Incremental$.apply(Incremental.scala:169)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2366)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2316)
[error]         at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:30)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:46)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:28)
[error]         at sbt.internal.io.Retry$.apply(Retry.scala:23)
[error]         at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:30)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2314)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /workspaces/shine/target/scala-2.13/classes/shine/DPIA/DSL/λ$.class
[error] Total time: 21 s, completed May 19, 2022 3:59:45 AM
```

**Comment by takatoyamada** [comment]
It's solved. I needed to properly set the locale setting on my environment for sbt, which is mentioned in [sbt document](https://www.scala-sbt.org/1.x/docs/Setup-Notes.html#Path+encoding).
If you encountered the same phenomenon, you could add `en_US.UTF-8` by `locale-gen en_US.UTF-8
`, and add environment variable by `export LC_CTYPE="en_US.UTF-8"`.

**Comment by Bastacyclop** [comment]
Hi @takatoyamada, and sorry for the late reply. We've encountered similar errors a while back but I can't remember how we fixed it. Glad to see that you've found a solution!
