### ISSUE TITLE
Gaussian algorithm [BUG]

### ISSUE THREAD

**Issue by johanneslenfers** [rise-lang/shine#97]
**Reproduce**
Run test "baseline" [here](https://github.com/rise-lang/shine/blob/gauss/src/test/scala/rise/elevate/gauss.scala) 

**Implementation**
Implementation is inspired by this [LIFT implementation](https://gitlab.com/larisa.stoltzfus/liftstencil-cgo2018-artifact/-/blob/master/benchmarks/figure8/workflow2/gaussian/small/gaussian.lift)
```
  val gaussWeights = List(
    List(2,4,5,4,2),
    List(4,9,12,9,4),
    List(5,12,15,12,5),
    List(4,9,12,9,4),
    List(2,4,5,4,2)
  )

  val N = 1024
  val M = 1024


  val gauss: Rise = //infer(
    fun(ArrayType(N, ArrayType(M, f32)))(in =>
      fun(ArrayType(5, ArrayType(5, f32)))(weights =>
        in |> padClamp2D(2) // in: NxM -> (N+4) x (M+4)
          |> slide2D(5,2) // -> MxN of 5x5 slides
          |> map(map(fun(sector => // sector:5x5
            zip(sector)(weights) //(v,w)
            |> map(fun(rowPair =>
              zip(fst(rowPair))(snd(rowPair))
              |> map(fun(pair =>
                fst(pair) * snd(pair)
              )) |> reduce(add)(l(0.0f))
            )) |> reduce(add)(l(0.0f))
        )))
      )
    )
```
**Error Message**
```
[BASELINE] rewrite time: 0s
skipping type inference
free variable _n53


expression is not in closed form:  λe1 λe2 mapSeq
         ┝ λη142 mapSeq
         │       ┝ λe16 let
         │       │      ┝ reduceSeq <λη150. λη158. add η150 η158> (<λe166. e166> 0.0000)
         │       │      │ ┕ mapSeq
         │       │      │   ┝ λe20 let
         │       │      │   │      ┝ reduceSeq <λη146. λη154. add η146 η154> (<λe162. e162> 0.0000)
         │       │      │   │      │ ┕ mapSeq <λe28. mul (fst e28) (snd e28)>
         │       │      │   │      │   ┕ zip (fst e20) (snd e20)
         │       │      │   │      ┕ λe116. e116
         │       │      │   ┕ zip e16 e2
         │       │      ┕ λe129. e129
         │       ┕ η142
         ┕ map transpose
           ┕ slide 5 2
             ┕ map (slide 5 2)
               ┕ padClamp 2 2 (map (padClamp 2 2) e1)

 with type (1024.1024.f32 -> (5.5.f32 -> _n50._n53.f32))
java.lang.Exception: expression is not in closed form:  λe1 λe2 mapSeq
         ┝ λη142 mapSeq
         │       ┝ λe16 let
         │       │      ┝ reduceSeq <λη150. λη158. add η150 η158> (<λe166. e166> 0.0000)
         │       │      │ ┕ mapSeq
         │       │      │   ┝ λe20 let
         │       │      │   │      ┝ reduceSeq <λη146. λη154. add η146 η154> (<λe162. e162> 0.0000)
         │       │      │   │      │ ┕ mapSeq <λe28. mul (fst e28) (snd e28)>
         │       │      │   │      │   ┕ zip (fst e20) (snd e20)
         │       │      │   │      ┕ λe116. e116
         │       │      │   ┕ zip e16 e2
         │       │      ┕ λe129. e129
         │       ┕ η142
         ┕ map transpose
           ┕ slide 5 2
             ┕ map (slide 5 2)
               ┕ padClamp 2 2 (map (padClamp 2 2) e1)

 with type (1024.1024.f32 -> (5.5.f32 -> _n50._n53.f32))
	at shine.DPIA.fromRise$.apply(fromRise.scala:17)
	at util.gen$.toDPIA(gen.scala:10)
	at util.gen$.CProgram(gen.scala:14)
	at rise.elevate.gauss.run(gauss.scala:108)
	at rise.elevate.gauss.$anonfun$new$1(gauss.scala:64)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:187)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:199)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:181)
	at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:232)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:231)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:236)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:235)
	at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1562)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1308)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1308)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1474)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)



Process finished with exit code 0

```

**Comment by Bastacyclop** [comment]
@johanneslenfers The issue is that both the "untyped" DSL and the `TypedDSL` are mixed in the same expression construction.
This results in some type information to be visible and type inference to be short-cirtcuited as the "skipping type inference" message shows.
https://github.com/rise-lang/shine/blob/3b158af739f46f91872ff05152a8da4587a74260/src/main/scala/rise/core/types/infer.scala#L14-L17
So, you end up with a half-typed expression which still has free variables that were not infered.
Commenting out the short-circuiting code makes the high level expression type check without issues.

You could simply update this branch with the new master where there is only a single DSL and such mix-up cannot happen.

**Comment by johanneslenfers** [comment]
Thanks, we now have this error: 

#### Updated Implementation

```
 val N = 1024
  val M = 1024

  val mulPair = fun(pair => fst(pair) * snd(pair))

  val gauss: Rise = { //infer(
    fun(ArrayType(N, ArrayType(M, f64)))(in =>
      fun(ArrayType(5, ArrayType(5, f64)))(weights =>
        in |> padClamp2D(2) // in: NxM -> (N+4) x (M+4)
          |> slide2D(5, 2) // -> MxN of 5x5 slides
          |> map(map(fun(sector => // sector:5x5
          zip(sector |> join)(weights |> join) |> map(mulPair) |> reduce(add)(l(0.0))
        )))
      )
    )
  
```
#### New Error Message
```
gauss:  λe7 λe8 map
         ┝ map
         │ ┕ λe78 reduce add 0.000000
         │        ┕ map <λe1. mul (fst e1) (snd e1)>
         │          ┕ zip (join e78) (join e8)
         ┕ λe77 map transpose
           │    ┕ <λe73. slide 5 2 (map (slide 5 2) e73)> e77
           ┕ <λe61. padClamp 2 2 (map (padClamp 2 2) e61)> e7
lowered: Success( λe7 λe8 mapSeq
         ┝ λη221 mapSeq
         │       ┝ λe78 let
         │       │      ┝ reduceSeq <λη225. λη229. add η225 η229> (<λe233. e233> 0.000000)
         │       │      │ ┕ mapSeq <λe1. mul (fst e1) (snd e1)>
         │       │      │   ┕ zip (join e78) (join e8)
         │       │      ┕ λe208. e208
         │       ┕ η221
         ┕ map <λη217. transpose η217>
           ┕ slide 5 2
             ┕ map <λη213. slide 5 2 η213>
               ┕ padClamp 2 2 (map <λη209. padClamp 2 2 η209> e7))


Failure when inferring access annotations for application:
 reduceSeq <λη225. λη229. add η225 η229> 0.000000
 ┕ mapSeq <λe1. mul (fst e1) (snd e1)>
   ┕ zip (join e78) (join e8)
with context:
Map( e7 -> exp[1024.1024.f64, read],  e8 -> exp[5.5.f64, read],  η221 -> exp[(1025*(1/^(2))).5.5.f64, access261],  e78 -> exp[5.5.f64, access262])
Cannot subunify exp[25.f64, write] <: exp[25.f64, read].
java.lang.Exception: Failure when inferring access annotations for application:
 reduceSeq <λη225. λη229. add η225 η229> 0.000000
 ┕ mapSeq <λe1. mul (fst e1) (snd e1)>
   ┕ zip (join e78) (join e8)
with context:
Map( e7 -> exp[1024.1024.f64, read],  e8 -> exp[5.5.f64, read],  η221 -> exp[(1025*(1/^(2))).5.5.f64, access261],  e78 -> exp[5.5.f64, access262])
Cannot subunify exp[25.f64, write] <: exp[25.f64, read].
	at shine.DPIA.package$.error(package.scala:15)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:177)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:169)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:168)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferLambda(InferAccessAnnotation.scala:155)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:128)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:169)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:168)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferLambda(InferAccessAnnotation.scala:155)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:128)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:169)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferApp(InferAccessAnnotation.scala:168)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:130)
	at shine.DPIA.InferAccessAnnotation.inferLambda(InferAccessAnnotation.scala:155)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:128)
	at shine.DPIA.InferAccessAnnotation.inferLambda(InferAccessAnnotation.scala:155)
	at shine.DPIA.InferAccessAnnotation.inferPhraseTypes(InferAccessAnnotation.scala:128)
	at shine.DPIA.InferAccessAnnotation.apply(InferAccessAnnotation.scala:30)
	at shine.DPIA.inferAccess$.apply(InferAccessAnnotation.scala:20)
	at shine.DPIA.fromRise$.apply(fromRise.scala:21)
	at util.gen$.$anonfun$exprToPhrase$1(gen.scala:137)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
	at rise.elevate.gauss.$anonfun$new$1(gauss.scala:80)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:187)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:199)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:181)
	at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:232)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:231)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:236)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:235)
	at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1562)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1308)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1308)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1474)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:41)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)



Process finished with exit code 0

```

**Comment by bastian-koepcke** [comment]
`exp[T, write]` means that the expression can be used inside of a `toMem` or anything that can put things into memory. Additionally, an expression that is `write` is describing *how* to write to memory (parallelism or sequential, loop nests etc) but not where to write. A read expression is something that can be evaluated to a value. A write expression cannot be evaluated on its own, because the memory is not specified.

The input array to `reduceSeq` is a `mapSeq` meaning that the input expression is `write`. The `reduceSeq` primitive expects a `read` expression for the input array (and a `write` expression for the initial value).

The `mapSeq` describes *how* to write to memory (sequentially) but not *where* to write. Therefore, the input array expression must be wrapped into something that puts it into memory, like `let`.

The output of `reduceSeq` is a `read` expression, which means that there is no direct need to write the the reduce expression into memory.

**Comment by Bastacyclop** [comment]
@johanneslenfers is this issue still relevant?
